#!/bin/bash
export PATH=/usr/local/sbin/:/usr/local/bin/:$PATH
export LD_LIBARAY_PATH=/usr/local/lib64:/usr/local/lib:$LD_LIBARAY_PATH
[ -z "$1" ] && echo "$0 {WHY}
Rippersnapper will chomp down on SLURM and stop any future jobs from running!
" && exit 1
exec 1> >(logger -s -t $(basename $0)) 2>&1

WHY="$(echo "$1" | tr -d '\200-\377' | sed -e "s/'//g" -e 's/"//g' |  cut --bytes=-100)"
echo "chomping down on SLURM: $WHY"
#echo "$WHY" > /etc/THIS_IS_A_BAD_NODE.ncar

scontrol update NodeName=$(hostname -s) State=drain Reason="rippersnapper: $WHY"

